#!/usr/bin/env python3
import csv
from pathlib import Path

from make_genome_intervals import (
    build_intergenic,
    iter_gene_features,
    merge_intervals,
    to_local,
    write_intervals,
)
from subset_gff_by_region import record_overlaps_region


REPO_ROOT = Path(__file__).resolve().parents[1]
GENOMEINFO_DIR = REPO_ROOT / "genomeinfo"
GFF_PATH = GENOMEINFO_DIR / "TAIR10_GFF3_genes.gff"
COMMAND_LOG = GENOMEINFO_DIR / "interval_generation_commands.txt"


def exact_specs():
    return [
        {
            "label": "gene100_chr1_10000000",
            "chrom": "Chr1",
            "start_pos": 10000000,
            "gene_count": 100,
            "gene_out": GENOMEINFO_DIR / "gene100_chr1_10000000.csv",
            "intergene_out": GENOMEINFO_DIR / "intergene100_chr1_10000000.csv",
            "subset_out": GENOMEINFO_DIR / "TAIR10_GFF3_genes_subset_gene100_chr1_10000000.gff",
        },
        {
            "label": "gene100_chr2_18000000",
            "chrom": "Chr2",
            "start_pos": 18000000,
            "gene_count": 100,
            "gene_out": GENOMEINFO_DIR / "gene100_chr2_18000000.csv",
            "intergene_out": GENOMEINFO_DIR / "intergene100_chr2_18000000.csv",
            "subset_out": GENOMEINFO_DIR / "TAIR10_GFF3_genes_subset_gene100_chr2_18000000.gff",
        },
        {
            "label": "gene100_chr3_22000000",
            "chrom": "Chr3",
            "start_pos": 22000000,
            "gene_count": 100,
            "gene_out": GENOMEINFO_DIR / "gene100_chr3_22000000.csv",
            "intergene_out": GENOMEINFO_DIR / "intergene100_chr3_22000000.csv",
            "subset_out": GENOMEINFO_DIR / "TAIR10_GFF3_genes_subset_gene100_chr3_22000000.gff",
        },
        {
            "label": "gene100_chr4_2000000",
            "chrom": "Chr4",
            "start_pos": 2000000,
            "gene_count": 100,
            "gene_out": GENOMEINFO_DIR / "gene100_chr4_2000000.csv",
            "intergene_out": GENOMEINFO_DIR / "intergene100_chr4_2000000.csv",
            "subset_out": GENOMEINFO_DIR / "TAIR10_GFF3_genes_subset_gene100_chr4_2000000.gff",
        },
    ]


def write_gff_subset(gff_path, chrom, region_start, region_end, out_path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(gff_path, newline="") as src, open(out_path, "w", newline="") as dst:
        dst.write(f"##subset chrom={chrom} start={region_start} end={region_end}\n")
        for raw_line in src:
            if not raw_line.strip():
                continue
            if raw_line.startswith("#"):
                dst.write(raw_line)
                continue

            fields = raw_line.rstrip("\n").split("\t")
            if len(fields) < 9 or fields[0] != chrom:
                continue
            if record_overlaps_region(fields, region_start, region_end):
                dst.write(raw_line)


def generate_exact_interval_pair(spec):
    raw_genes = []
    for start, stop in iter_gene_features(GFF_PATH, spec["chrom"], spec["start_pos"]):
        raw_genes.append((start, stop))
        if len(raw_genes) == spec["gene_count"] + 1:
            break

    if len(raw_genes) < spec["gene_count"]:
        raise SystemExit(
            f"Found only {len(raw_genes)} genes for {spec['label']}, expected {spec['gene_count']}."
        )

    selected_genes = raw_genes[: spec["gene_count"]]
    next_gene = raw_genes[spec["gene_count"]] if len(raw_genes) > spec["gene_count"] else None

    region_start = spec["start_pos"]
    region_end = next_gene[0] - 1 if next_gene is not None else max(stop for _, stop in selected_genes)
    region_length = region_end - region_start + 1

    merged_genes = merge_intervals(selected_genes)
    merged_genes_local = to_local(merged_genes, region_start)
    intergenic_local = build_intergenic(merged_genes_local, region_length)

    write_intervals(spec["gene_out"], merged_genes_local, "g2")
    write_intervals(spec["intergene_out"], intergenic_local, "g1")
    write_gff_subset(GFF_PATH, spec["chrom"], region_start, region_end, spec["subset_out"])

    return {
        "chrom": spec["chrom"],
        "region_start": region_start,
        "region_end": region_end,
    }


def read_interval_end(*paths):
    region_end = 0
    for path in paths:
        with open(path, newline="") as handle:
            for row in csv.reader(handle):
                if row:
                    region_end = max(region_end, int(row[1]))
    return region_end


def build_command_log(exact_outputs):
    lines = [
        "# Commands and notes for the genomeinfo interval files",
        "# Generated by scripts/build_genomeinfo_assets.py",
        "",
        "# Chr5 legacy pair",
        "# genomeinfo/gene100_chr5_1.csv matches the merged intervals from the",
        "# first 113 gene features on Chr5. The paired intergene100_chr5_1.csv matches the",
        "# corresponding leading/internal intergenic gaps and omits the final trailing",
        "# gap before the next gene. We keep this setup because existing simulations",
        "# are based on it.",
        (
            "python3 scripts/subset_gff_by_region.py "
            "--gff genomeinfo/TAIR10_GFF3_genes.gff "
            "--chrom Chr5 --start 1 --end 377208 "
            "--out genomeinfo/TAIR10_GFF3_genes_subset_gene100.gff"
        ),
        "",
    ]

    for spec, output in zip(exact_specs(), exact_outputs):
        lines.extend(
            [
                f"# {spec['label']}",
                (
                    "python3 scripts/make_genome_intervals.py "
                    f"--gff genomeinfo/TAIR10_GFF3_genes.gff "
                    f"--chrom {spec['chrom']} --start-pos {spec['start_pos']} "
                    f"--gene-out genomeinfo/{spec['gene_out'].name} "
                    f"--intergene-out genomeinfo/{spec['intergene_out'].name}"
                ),
                (
                    "python3 scripts/subset_gff_by_region.py "
                    "--gff genomeinfo/TAIR10_GFF3_genes.gff "
                    f"--chrom {output['chrom']} --start {output['region_start']} --end {output['region_end']} "
                    f"--out genomeinfo/{spec['subset_out'].name}"
                ),
                "",
            ]
        )

    COMMAND_LOG.write_text("\n".join(lines))


def main():
    exact_outputs = [generate_exact_interval_pair(spec) for spec in exact_specs()]

    write_gff_subset(
        GFF_PATH,
        "Chr5",
        1,
        read_interval_end(
            GENOMEINFO_DIR / "gene100_chr5_1.csv",
            GENOMEINFO_DIR / "intergene100_chr5_1.csv",
        ),
        GENOMEINFO_DIR / "TAIR10_GFF3_genes_subset_gene100.gff",
    )

    build_command_log(exact_outputs)
    print(f"Wrote {COMMAND_LOG}")


if __name__ == "__main__":
    main()
